server:
  port: 8101

spring:
  datasource:
    url: jdbc:postgresql://database:5432/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
      ddl-auto: validate
